const firstNames = [
    { name: "James", gender: "male" },
    { name: "Mary", gender: "female" },
    { name: "John", gender: "male" },
    { name: "Patricia", gender: "female" },
    { name: "Robert", gender: "male" },
    { name: "Jennifer", gender: "female" },
    { name: "Michael", gender: "male" },
    { name: "Linda", gender: "female" },
    { name: "William", gender: "male" },
    { name: "Elizabeth", gender: "female" },
    { name: "David", gender: "male" },
    { name: "Susan", gender: "female" },
    { name: "Richard", gender: "male" },
    { name: "Jessica", gender: "female" },
    { name: "Joseph", gender: "male" },
    { name: "Sarah", gender: "female" },
    { name: "Charles", gender: "male" },
    { name: "Karen", gender: "female" },
    { name: "Thomas", gender: "male" },
    { name: "Nancy", gender: "female" },
    { name: "Daniel", gender: "male" },
    { name: "Margaret", gender: "female" },
    { name: "Matthew", gender: "male" },
    { name: "Lisa", gender: "female" },
    { name: "Christopher", gender: "male" },
    { name: "Betty", gender: "female" },
    { name: "George", gender: "male" },
    { name: "Dorothy", gender: "female" },
    { name: "Edward", gender: "male" },
    { name: "Sandra", gender: "female" },
    { name: "Kenneth", gender: "male" },
    { name: "Ashley", gender: "female" },
    { name: "Anthony", gender: "male" },
    { name: "Kimberly", gender: "female" },
    { name: "Brian", gender: "male" },
    { name: "Donna", gender: "female" },
    { name: "Ronald", gender: "male" },
    { name: "Emily", gender: "female" },
    { name: "Timothy", gender: "male" },
    { name: "Carol", gender: "female" },
    { name: "Kevin", gender: "male" },
    { name: "Michelle", gender: "female" },
    { name: "Thomas", gender: "male" },
    { name: "Laura", gender: "female" },
    { name: "Donald", gender: "male" },
    { name: "Susan", gender: "female" },
    { name: "Gary", gender: "male" },
    { name: "Kathleen", gender: "female" }
];

const lastNames = [
    'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia', 'Rodriguez', 'Martinez',
    'Wilson', 'Anderson', 'Taylor', 'Thomas', 'Moore', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
    'Garcia', 'Martinez', 'Robinson', 'Clark', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young',
    'King', 'Wright', 'Scott', 'Adams', 'Green', 'Baker', 'Hill', 'Carter', 'Mitchell', 'Evans',
    'Gray', 'Morgan', 'Cooper', 'Murphy', 'Peterson', 'Cook', 'Bell', 'Bailey', 'Rivera', 'Wood',
    'Reed', 'Stewart', 'Morris', 'Sanchez', 'Rogers', 'Fisher', 'Richardson', 'Cole', 'Jenkins', 'Perry',
    'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzales',
    'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes', 'Myers', 'Ford', 'Hamilton', 'Graham',
    'Sullivan', 'Wallace', 'Woods', 'Coleman', 'West', 'Jordan', 'Owens', 'Reynolds', 'Fisher', 'Ellis',
    'Harrison', 'Gibson', 'Mcdonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray', 'Freeman', 'Wells'
];

module.exports = {
    firstNames,
    lastNames
}